language: java

addons:
  postgresql: "9.3"

before_script:
  - psql -U postgres -c "create database spatialdata"
  - psql -U postgres -d spatialdata -c "create extension postgis"

script:
  - mvn verify

after_success:
  - mvn deploy -s deploy-settings.xml
