language: java

addons:
  postgresql: "9.5"

before_script:
  - psql -U postgres -c "create user docker with password 'docker'"
  - psql -U postgres -c "create database geoladris_tests owner = docker"
  - psql -U postgres -d geoladris_tests -c "create extension postgis"

script:
  - mvn verify -Pintegration-tests

after_success:
  - mvn deploy -s deploy-settings.xml

